app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', 'WelcomeController@index');

//Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/',     'HomeController@index');
Route::get('admin/home/', 'HomeController@index');

// Route::post('users/store', 'UserController@store');

Route::group(['prefix' => 'admin','middleware' => ['auth']], function(){
	Route::get('events/get_all', 'EventsController@get_all');
	Route::resource('events', 'EventsController');

	Route::get('offers/get_all', 'OffersController@get_all');
	Route::resource('offers', 'OffersController');

	Route::resource('redeemeds', 'RedeemedsController');	

	Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
});

Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function(){

	Route::resource('user', 'UserController');
	Route::get('brands/get_all','BrandsController@get_all');
	Route::resource('brands','BrandsController');

	Route::get('zones/get_all', 'ZonesController@get_all');
	Route::resource('zones', 'ZonesController');

	Route::get('partners/get_all', 'PartnersController@get_all');
	Route::resource('partners', 'PartnersController');


	Route::post('importExcel','PartnersController@importExcel');

	Route::post('reset_password',['as' => 'admin.partners.reset_password','uses' =>'PartnersController@reset_password']);
});

Route::group(['prefix'=>'admin'], function(){
Route::post('newpassword',['as' => 'admin.newpassword','uses' =>'UserController@newpassword']);
});

Route::group(['prefix'=>'v1'], function(){
	Route::post('users/store', 'UserController@store');
	Route::get('zones/list','ZonesController@nearbyzones');
	Route::get('partners/get_partners/{id}', 'PartnersController@get_partners');
	Route::get('partners/details/{id}','PartnersController@details');
	Route::get('offers/view/{offer_id}', 'OffersController@view_offer');
	Route::get('events/list','EventsController@nearbyevents');
	Route::get('events/view/{id}', 'EventsController@view_event');

	Route::get('events/notification', 'EventsController@event_notify');
	
	Route::post('redeemeds/redeem_offer', 'RedeemedsController@redeem_offer');
	Route::get('redeemeds/user_redeemed', 'RedeemedsController@user_redeem_offer');
	Route::get('zones/search', 'ZonesController@search_zones');
	Route::get('events/search', 'EventsController@search_events');
	Route::get('offers/list', 'OffersController@nearbyofffers');
	Route::get('offers/birthdayoffers/{user_id}', 'OffersController@birthday_offers');
	Route::get('offers/search', 'OffersController@search_offers');
	Route::get('notification', 'UserController@notify');	
	Route::post('users/location', 'UserController@user_location');	
	Route::post('users/favourite', 'UserController@user_favourites');
	Route::post('users/favouritelist', 'UserController@user_favourite_list');
});

app/Http/Controllers/EventsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateEventsFormRequest;

use Illuminate\Http\Request;
use App\Model\Events;
use Input;
use DB;
use LaravelFCM\Message\OptionsBuilder;
use LaravelFCM\Message\PayloadDataBuilder;
use LaravelFCM\Message\PayloadNotificationBuilder;
use FCM;
use App\Model\Notifications;

class_alias(\LaravelFCM\Facades\FCM::class, 'FCM');
class_alias(\LaravelFCM\Facades\FCMGroup::class, 'FCMGroup');

class EventsController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		if(\Auth::user()->type == 'admin'){
			$events = Events::orderBy('id', 'desc')->get();
		}elseif(\Auth::user()->type == 'partner'){
			$events = Events::where('created_by',\Auth::user()->id)->orderBy('id', 'desc')->get();
		}
		
		return View('backend.events.index',compact('events'));
	}

	public function get_all()
	{
		$events = Events::all();
		return response()->json(['aaData' => $events]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		$today_date = date('Y-m-d');
		$event_type = array('local'=>'Local','mega'=>'Mega');
		$invite_to = array('partners'=>'Partners', 'general_users'=>'General Users','both'=>'Both');
		return View('backend.events.create', compact('event_type','invite_to','today_date'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateEventsFormRequest $request)
	{
		//
		$fileName = '';
		if (Input::file('image') && Input::file('image')->isValid()) {
			$destinationPath = 'uploads/events'; // upload path
			$extension = Input::file('image')->getClientOriginalExtension(); // getting image extension
			$fileName = rand(11111,99999).'.'.$extension; // renameing image
			Input::file('image')->move($destinationPath, $fileName); // uploading file to given path
		}
		$event = Events::create([
			'name'=>$request->input('name'),
			'type'=>$request->input('type'),
			'image'=>$fileName,
			'start_date'=>$request->input('start_date'),
			'end_date'=>$request->input('end_date'),
			'city'=>$request->input('city'),
			'location'=>$request->input('location'),
			'description'=>$request->input('description'),
			'invite_to'=>$request->input('invite_to'),
			'latitude'=>$request->input('latitude'),
			'longitude'=>$request->input('longitude'),
			'created_by'=>\Auth::user()->id,
			'updated_by'=>\Auth::user()->id
			]);
		if($event){
			$request->session()->flash('success-message', 'Succesfully Inserted');
		}else{
			$request->session()->flash('error-message', 'Insert Failed');
		}
		
		if(Input::get('save_notify')) {
	
			$optionBuiler = new OptionsBuilder();
			$optionBuiler->setTimeToLive(60*20);
			$notification_title = $request->input('name');
			$notification_body = $request->input('description');


			$notificationBuilder = new PayloadNotificationBuilder($notification_title);
			$notificationBuilder->setBody($notification_body)
			                    ->setSound('default')
			                    ->setIcon('fcm_push_icon')
			                    ->setClickAction('FCM_PLUGIN_ACTIVITY');

			$dataBuilder = new PayloadDataBuilder();
			$dataBuilder->addData(['title' => $notification_title,'body'=>$notification_body,'id'=>$event->id]);
			$option = $optionBuiler->build();
			$notification = $notificationBuilder->build();
			$data = $dataBuilder->build();

			if(isset($_GET['debug'])) {
				print_r($data);
				print_r($option);
				print_r($notification);
				die();
			}

			// You must change it to get your tokens
			
			$push_ids = Notifications::select(DB::raw('array_to_string(array_agg(DISTINCT push_id), \',\') as push_ids'))->get();
			$tokens = explode(",", $push_ids[0]->push_ids);

			
			$downstreamResponse = FCM::sendTo($tokens, $option, $notification,$data);
			 //print_r($downstreamResponse);
			echo "success count ".$downstreamResponse->numberSuccess();
			echo "failure count ".$downstreamResponse->numberFailure(); 
			echo "modifiction count ".$downstreamResponse->numberModification();

			//return Array - you must remove all this tokens in your database
			$downstreamResponse->tokensToDelete(); 

			//return Array (key : oldToken, value : new token - you must change the token in your database )
			$downstreamResponse->tokensToModify(); 

			//return Array - you should try to resend the message to the tokens in the array
			$downstreamResponse->tokensToRetry();

         
         }
		
	die('hello');
		return redirect('admin/events');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{

		$event_info = Events::where('id',$id)->get();
		// print_r($event_info->toArray());die('hello');

		// $offer_partners = Offer_partners::with('user')->select('user_id')->where('offer_id',$id)->get();

		// $offer_zones = Offer_zones::with('zone')->select('zone_id')->where('offer_id',$id)->get();
		
		return View('backend.events.show',compact('event_info'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		$today_date = date('Y-m-d');
		$event_type = array('local'=>'Local','mega'=>'Mega');
		$invite_to = array('partners'=>'Partners', 'general_users'=>'General Users','both'=>'Both');
		$event_info = Events::where('id',$id)->get();
		return View('backend.events.edit',compact('event_info','event_type','invite_to','today_date'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, CreateEventsFormRequest $request)
	{
		//
		$event_info = Events::where('id',$id)->get();
		$fileName = $event_info[0]->image;
		if (Input::file('image')) {
			$destinationPath = 'uploads/events'; // upload path
			$extension = Input::file('image')->getClientOriginalExtension(); // getting image extension
			$fileName = rand(11111,99999).'.'.$extension; // renameing image
			Input::file('image')->move($destinationPath, $fileName); // uploading file to given path
			@unlink('uploads/events/'.$event_info[0]->image);
		}
		$event = Events::where('id',$id)->update([
			'name'=>$request->input('name'),
			'type'=>$request->input('type'),
			'image'=>$fileName,
			'start_date'=>$request->input('start_date'),
			'end_date'=>$request->input('end_date'),
			'city'=>$request->input('city'),
			'location'=>$request->input('location'),
			'description'=>$request->input('description'),
			'invite_to'=>$request->input('invite_to'),
			'latitude'=>$request->input('latitude'),
			'longitude'=>$request->input('longitude'),
			'updated_by'=>\Auth::user()->id
			]);
		if($event){
			$request->session()->flash('success-message', 'Succesfully Updated');
		}else{
			$request->session()->flash('error-message', 'Update Failed');
		}
		return redirect('admin/events');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id,Request $request)
	{
		//
		Events::where('id',$id)->update([
			'deleted_by'=>\Auth::user()->id
			]);

		$result= Events::destroy($id);
		if($result){
			$request->session()->flash('success-message', 'Succesfully Deleted');
		}else{
			$request->session()->flash('error-message', 'Delete Failed');
		}
		return redirect('admin/events');
	}

	public function nearbyevents(Request $request)
	{
		$per_page = 5;
		$latitude = $request->input('lat');
		$longitude = $request->input('lng');
		$offset = ($request->input('offset'))?$request->input('offset'):0;
		$required_offset = ($offset>0)?(($offset-1)*$per_page):$offset;

		$results = DB::select('SELECT * FROM (SELECT id,name, image, city,location,start_date, end_date, latitude, longitude, (3959 * acos(cos(radians(:lat :: FLOAT)) * cos(radians(latitude :: FLOAT)) * cos(radians(longitude :: FLOAT) - radians(:lng :: FLOAT)) + sin(radians(:lat :: FLOAT)) * sin(radians(latitude :: FLOAT)))) * 1.6 AS distance_in_km, DATE(end_date) - DATE(CURRENT_DATE) as datediff FROM events WHERE deleted_at IS NULL) AS tbl where datediff >= 0 order by distance_in_km ASC OFFSET :offset LIMIT :per_page', ['lat'=>$latitude,'lng'=>$longitude, 'offset'=>$required_offset, 'per_page'=>$per_page]);
		return response()->json(["events"=>$results, "status"=>1], 201);
	}

	public function view_event($id)
	{
		$event_info = Events::where('id',$id)->get();

		return response()->json(["event_info"=>$event_info[0], "status"=>1], 201);
	}

	public function search_events(Request $request)
	{
		$per_page = 5;
		$keywords = strtolower($request->keywords);

		$offset = ($request->input('offset'))?$request->input('offset'):0;
		$required_offset = ($offset>0)?(($offset-1)*$per_page):$offset;

		$events = Events::where(function ($query) use ($keywords){
			                $query->where('name', 'ilike', '%' . $keywords . '%')
			                		->orWhere('city', 'ilike', '%' . $keywords . '%')
			                		->orWhere('location', 'ilike', '%' . $keywords . '%');
			            })
                		->where(DB::raw('DATE(end_date) - DATE(CURRENT_DATE)'), '>=', 0)
						->offset($required_offset)
                		->limit($per_page)
                		->get();
        
		return response()->json(['events'=>$events,"status"=>1], 200);

	}

}

resources/views/backend/events/create.blade.php
@extends('backend/app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body ">
			<div class="bg-light lter b-b wrapper-md">
				<h1 class="m-n font-thin h3">Create New Event</h1>
			</div>
			<div class="wrapper-md" ng-controller="FormDemoCtrl">
				<div class="row">
				<div class="col-sm-12 col-md-12 col-xs-12">
				<div class="panel panel-default">
					<!-- <div class="panel-heading font-bold">
						Create New Event
					</div> -->
					<div class="panel-body">
						<!-- @if (count($errors) > 0)
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif -->
						{!! Form::open(['route' => 'admin.events.store','data-parsley-validate','files'=>true]) !!}
						{!! Form::hidden('latitude','27.7172453',['id'=>'latitude']) !!}
						{!! Form::hidden('longitude','85.3239605',['id'=>'longitude']) !!}
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('name', 'Title:', ['class' => 'control-label']) !!}
									{!! Form::text('name', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('type', 'Type:', ['class' => 'control-label']) !!}
									{!! Form::select('type',array(null=>'Please Select')+$event_type,null,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select type')) !!}


									@if ($errors->has('type')) <p class="help-block">{{ $errors->first('type') }}</p> @endif
								</div>
								
							</div>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('start_date', 'Start Date:', ['class' => 'control-label']) !!}
									{!! Form::text('start_date', null, ['class' => 'form-control datepick required','data-trigger'=>'change focusout','id'=>'start_date', 'readonly'=>'readonly']) !!}

									@if ($errors->has('start_date')) <p class="help-block">{{ $errors->first('start_date') }}</p> @endif
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('end_date', 'End Date:', ['class' => 'control-label']) !!}
									{!! Form::text('end_date', null, ['class' => 'form-control datepick required','data-trigger'=>'change focusout','id'=>'end_date', 'readonly'=>'readonly']) !!}

									@if ($errors->has('end_date')) <p class="help-block">{{ $errors->first('end_date') }}</p> @endif
								</div>
							</div>							
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('location', 'Location:', ['class' => 'control-label']) !!}
									{!! Form::text('location', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('location')) <p class="help-block">{{ $errors->first('location') }}</p> @endif
								</div>
								
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('city', 'City:', ['class' => 'control-label']) !!}
									{!! Form::text('city', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('city')) <p class="help-block">{{ $errors->first('city') }}</p> @endif
								</div>								
							</div>
						</div>

						

						<div class="row">
							<div class="col-md-6">								
								<div class="form-group">
									{!! Form::label('invite_to', 'Invite To:', ['class' => 'control-label']) !!}
																	
									@foreach($invite_to as $k => $v)
										<div class="radio">
							              <label class="i-checks i-checks-sm">
							                <input type="radio" name="invite_to" value="{{$k}}">
							                <i></i>
							               {{$v}}
							              </label>
							            </div>										
									@endforeach
									@if ($errors->has('invite_to')) <p class="help-block">{{ $errors->first('invite_to') }}</p> @endif
								</div>

								<div class="form-group">
									{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
									<!-- {!! Form::file('image', null, ['class' => 'form-control']) !!} -->
									<div class="image_select">
										<input type="file" name="image" id="file-1" class="inputfile inputfile-6 required" data-trigger="change focusout" data-multiple-caption="{count} files selected" multiple />
										<label for="file-1"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Choose a Image&hellip;</strong></label>
									</div>										
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('description', 'Description:', ['class' => 'control-label']) !!}
									{!! Form::textarea('description', null, ['class' => 'form-control required','data-trigger'=>'change focusout','rows'=>7]) !!}

									@if ($errors->has('description')) <p class="help-block">{{ $errors->first('description') }}</p> @endif
								</div>
							</div>
						</div>

						<div class="form-group">
							<input id='search_address' name="search_address" class='form-control' type='text' value='kathmandu, Nepal' placeholder='Search Box'>
							<div id="display_map" style="height:500px"></div>							
						</div>
						
						<button type="submit" name="save_event" value="save_event" class="btn btn-sm btn-primary">Submit</button>
						<button type="submit" name="save_notify" value="save_and_notify" class="btn btn-sm btn-primary">Submit And Push</button>
						<button type="reset" class="btn btn-sm btn-primary" onclick="window.location.href='<?php echo URL::to('admin/events');?>'"">Cancel</button>
						</form>
					</div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/backend/events/edit.blade.php
@extends('backend/app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body ">
			<div class="bg-light lter b-b wrapper-md">
				<h1 class="m-n font-thin h3">Update Event</h1>
			</div>
			<div class="wrapper-md" ng-controller="FormDemoCtrl">
				<div class="row">
				<div class="col-sm-12 col-md-12 col-xs-12">
				<div class="panel panel-default">
					<div class="panel-heading font-bold">
						Update Event
					</div>
					<div class="panel-body">
						@if (count($errors) > 0)
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif
						{!! Form::model($event_info,['id'=>'events-update','route' => ['admin.events.update', $event_info[0]->id], 'method' => 'patch','data-parsley-validate','files'=>true]) !!}
						{!! Form::hidden('latitude',$event_info[0]->latitude,['id'=>'latitude']) !!}
						{!! Form::hidden('longitude',$event_info[0]->longitude,['id'=>'longitude']) !!}
						
						<div class="row">
							<div class="col-md-6">
									<div class="form-group">
										{!! Form::label('name', 'Title:', ['class' => 'control-label']) !!}
										{!! Form::text('name', $event_info[0]->name, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
										{!! Form::file('image', null, ['class' => 'form-control']) !!}
										@if($event_info[0]->image != '')
											<img src="{{ asset('uploads/events/'.$event_info[0]->image)}}" style="height: 100px; margin-top: 10px;" />
										@endif
									</div>

									<div class="form-group">
										{!! Form::label('type', 'Type:', ['class' => 'control-label']) !!}
										{!! Form::select('type',array(null=>'Please Select')+$event_type,$event_info[0]->type,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select type')) !!}
									</div>

									<div class="form-group">
										{!! Form::label('start_date', 'Start Date:', ['class' => 'control-label']) !!}
										{!! Form::text('start_date', $event_info[0]->start_date, ['class' => 'form-control datepick required','id'=>'start_date','readonly'=>'readonly','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										{!! Form::label('end_date', 'End Date:', ['class' => 'control-label']) !!}
										{!! Form::text('end_date', $event_info[0]->end_date, ['class' => 'form-control datepick required','id'=>'end_date','readonly'=>'readonly','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										{!! Form::label('city', 'City:', ['class' => 'control-label']) !!}
										{!! Form::text('city', $event_info[0]->city, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										{!! Form::label('location', 'Location:', ['class' => 'control-label']) !!}
										{!! Form::text('location', $event_info[0]->location, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										{!! Form::label('invite_to', 'Invite To:', ['class' => 'control-label']) !!}
										@foreach($invite_to as $k => $v)
											{!! Form::radio('invite_to',$k, ($k == $event_info[0]->invite_to)?true:false) !!}
											{!! Form::label($v) !!}
										@endforeach
									</div>

									<div class="form-group">
										{!! Form::label('description', 'Description:', ['class' => 'control-label']) !!}
										{!! Form::textarea('description', $event_info[0]->description, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
									</div>

									<div class="form-group">
										<input id='search_address' name="search_address" class='form-control' type='text' value='kathmandu, Nepal' placeholder='Search Box'>
										<div id="display_map" style="height:500px"></div>							
									</div>
						
									<button type="submit" name="save_event" class="btn btn-sm btn-primary">Submit</button>
									<button type="reset" class="btn btn-sm btn-primary" onclick="window.location.href='<?php echo URL::to('admin/events');?>'"">Cancel</button>
							</div>
						</div>
						
						</form>
					</div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/backend/events/index.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">Events</h1>
		</div>
		<div class="wrapper-md">
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{{url('admin/events/create')}}" class="btn btn-sm btn-primary btn-addon"><i class="fa fa-plus"></i>Add New Event</a>
				</div>
				<div class="table-responsive">
					<table ui-jq="dataTable" ui-options="" class="table table-striped m-b-none">
						<thead>
							<tr>
								<th style="width:20%">SN</th>
								<th style="width:25%">Name</th>
								<th>Start Date</th>
								<th>End Date</th>
								<th>Location</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						@if($events)
							<?php $i = 1; ?>
							@foreach($events as $event)
								<tr>
									<td>{{$i}}</td>
									<td>{{$event->name}}</td>
									<td>{{$event->start_date}}</td>
									<td>{{$event->end_date}}</td>
									<td>{{$event->location}}</td>
									<td>
										<a href="{{ route('admin.events.show',$event->id) }}" class="view btn btn-success btn-single" data-toggle="tooltip" title="Detail"><i class="fa fa-file-text-o"></i></a>
										<a class="edit btn btn-success btn-single" data-toggle="tooltip" title="Edit" href="{{ route('admin.events.edit', $event->id) }}"><i class="fa fa-edit"></i></a>
										{!! Form::open(['method' => 'DELETE', 'route'=>['admin.events.destroy', $event->id],'onsubmit' => 'return confirm("Do you want to delete this event?")']) !!}
										<!-- {!!Form::button('<i class="icon icon-trash"></i> ', array('type' => 'submit')); !!} -->
										{!!Form::button('<i class="icon icon-trash"></i> ', array(
									           'type' => 'submit',
									           'title' => 'Delete',
									           'data-toggle' => 'tooltip',
									           'class'=> 'btn btn-success btn-single',
									           'onclick'=>'return confirm("Are you sure?")'
									   	)); !!}
										{!! Form::close() !!}
									</td>
								</tr>
								<?php $i++; ?>
							@endforeach
						@else
							No events added yet.
						@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/events/show.blade.php
@extends('backend/app')
@section('content')
  <div id="content" class="app-content" role="main">
    <div class="app-content-body ">
      <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Event Detail</h1>
      </div>
      <div class="wrapper-md" ng-controller="FormDemoCtrl">
        <div class="row">
        <div class="col-md-12">
        <div class="panel panel-default">
          <!-- <div class="panel-heading font-bold">
            Create New Zone
          </div> -->
          {!! Form::hidden('latitude',$event_info[0]->latitude,['id'=>'latitude']) !!}
            {!! Form::hidden('longitude',$event_info[0]->longitude,['id'=>'longitude']) !!}
          <div class="panel-body">
            <div class="row">
            <?php ?>
            <table>
              <tr>
                  <td>Image</td>                   
                  <td><img src="{{ asset('uploads/events/'.$event_info[0]->image)}}" style="height: 100px; margin-top: 10px;" /></td>
               </tr>
              <tr>
                  <td>Type</td>                   
                  <td>{{$event_info[0]->type}}</td>
               </tr>
               <tr>
                  <td>City</td>                   
                  <td>{{$event_info[0]->city}}</td>
               </tr>
               @if($event_info[0]->type=='general')
               <tr>
                  <td>Start Date</td>                   
                  <td>{{$event_info[0]->start_date}}</td>
               </tr>
               <tr>
                  <td>End Date</td>                   
                  <td>{{$event_info[0]->end_date}}</td>
               </tr>
               @endif
                <tr>
                  <td>Description</td>                   
                  <td>{{$event_info[0]->description}}</b></td>
               </tr>
              </table>
            </div>
         </div>
      </div>
      <div class="form-group">
           <div id="display_map" style="height:500px"></div>             
      </div>      
</div>
</div>
</div>
</div>
@endsection