app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', 'WelcomeController@index');

//Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/',     'HomeController@index');
Route::get('admin/home/', 'HomeController@index');

// Route::post('users/store', 'UserController@store');

Route::group(['prefix' => 'admin','middleware' => ['auth']], function(){
	Route::get('events/get_all', 'EventsController@get_all');
	Route::resource('events', 'EventsController');

	Route::get('offers/get_all', 'OffersController@get_all');
	Route::resource('offers', 'OffersController');

	Route::resource('redeemeds', 'RedeemedsController');	

	Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
});

Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function(){

	Route::resource('user', 'UserController');
	Route::get('brands/get_all','BrandsController@get_all');
	Route::resource('brands','BrandsController');

	Route::get('zones/get_all', 'ZonesController@get_all');
	Route::resource('zones', 'ZonesController');

	Route::get('partners/get_all', 'PartnersController@get_all');
	Route::resource('partners', 'PartnersController');


	Route::post('importExcel','PartnersController@importExcel');

	Route::post('reset_password',['as' => 'admin.partners.reset_password','uses' =>'PartnersController@reset_password']);
});

Route::group(['prefix'=>'admin'], function(){
Route::post('newpassword',['as' => 'admin.newpassword','uses' =>'UserController@newpassword']);
});

Route::group(['prefix'=>'v1'], function(){
	Route::post('users/store', 'UserController@store');
	Route::get('zones/list','ZonesController@nearbyzones');
	Route::get('partners/get_partners/{id}', 'PartnersController@get_partners');
	Route::get('partners/details/{id}','PartnersController@details');
	Route::get('offers/view/{offer_id}', 'OffersController@view_offer');
	Route::get('events/list','EventsController@nearbyevents');
	Route::get('events/view/{id}', 'EventsController@view_event');

	Route::get('events/notification', 'EventsController@event_notify');
	
	Route::post('redeemeds/redeem_offer', 'RedeemedsController@redeem_offer');
	Route::get('redeemeds/user_redeemed', 'RedeemedsController@user_redeem_offer');
	Route::get('zones/search', 'ZonesController@search_zones');
	Route::get('events/search', 'EventsController@search_events');
	Route::get('offers/list', 'OffersController@nearbyofffers');
	Route::get('offers/birthdayoffers/{user_id}', 'OffersController@birthday_offers');
	Route::get('offers/search', 'OffersController@search_offers');
	Route::get('notification', 'UserController@notify');	
	Route::post('users/location', 'UserController@user_location');	
	Route::post('users/favourite', 'UserController@user_favourites');
	Route::post('users/favouritelist', 'UserController@user_favourite_list');
});

app/Http/Controllers/PartnersController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreatePartnersFormRequest;
use App\Http\Requests\UpdatePartnersFormRequest;


use Illuminate\Http\Request;
use App\Model\Partners;
use App\Model\Brands;
use App\Model\Zones;
use App\Model\Offers;
use App\Model\Partner_brands;
use DB;
use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use Input;


class PartnersController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$partners = Partners::where('type','partner')->orderBy('id', 'desc')->get();
		return View('backend.partners.index', compact('partners'));
	}

	public function get_all()
	{
		$partners = Partners::where('type','partner')->get();
		return response()->json(['aaData' => $partners]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		$brands = Brands::all();
		$zones=Zones::get()->lists('name', 'id');
		return View('backend.partners.create',compact('brands','zones'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreatePartnersFormRequest $request)
	{
		//
		// DB::beginTransaction();




		try {

		 	$logo = '';
			if ($request->file('logo') && $request->file('logo')->isValid()) {
				$destinationPath = 'uploads/partners/logo'; // upload path
				$extension = $request->file('logo')->getClientOriginalExtension(); // getting image extension
				$logo = rand(11111,99999).'.'.$extension; // renameing image
				$request->file('logo')->move($destinationPath, $logo); // uploading file to given path

			}


			$background_image = '';
			if ($request->file('background_image') && $request->file('background_image')->isValid()) {
				$destinationPath = 'uploads/partners/backgrounds'; // upload path
				$extension = $request->file('background_image')->getClientOriginalExtension(); // getting image extension
				$background_image = rand(11111,99999).'.'.$extension; // renameing image
				$request->file('background_image')->move($destinationPath, $background_image); // uploading file to given path

			}


			$password = $this->create_password(8);

			$qr_code = $this->generate_qr_code();

			DB::enableQueryLog();

			$partner = Partners::create([
				'name'=>$request->input('name'),
				'email'=>$request->input('email'),
				'password'=>\Hash::make($password),
				'contact_person'=>$request->input('contact_person'),
				'designation'=>$request->input('designation'),
				'address'=>$request->input('address'),
				'city'=>$request->input('city'),
				'phone'=>$request->input('phone'),
				'type'=>$request->input('type'),
				'zone_id'=>$request->input('zone_id'),
				'qr_code'=>$qr_code,
				'logo'=>$logo,
				'background_image'=>$background_image,
				'is_facebook'=>$request->input('facebook_link'),
				'latitude' => $request->input('latitude'),
				'longitude' => $request->input('longitude'),
				'created_by'=>\Auth::user()->id,
				'updated_by'=>\Auth::user()->id
				]);
			$partner_id = $partner->id;
					
			foreach($request->input('brand_id') as $brand_id){
				$partner_brand = Partner_brands::create([
					'user_id'=>$partner_id,
					'brand_id'=>$brand_id,
					'created_by'=>\Auth::user()->id,
					'updated_by'=>\Auth::user()->id
					]);
			}
			$subject = 'User Credentials!';
			$message = "<html>
						    <body>
						    <p>Hi {$request->input('name')}</p>
						    <p>You have been registered in GB Web Application.Your login credential for is as below:</p>
							<span>Username: {$request->input('email')}</span><br/>
							<span>Password: {$password}</span>
						    </body>
						</html>";
			$headers = 'From: info@gbzone.ml' . "\r\n";
			$headers .='Reply-To:info@gbzone.ml' . "\r\n";
			$headers .= "MIME-Version: 1.0\r\n";
	        $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
	        $headers .= "X-Priority: 3\r\n";
	        $headers .= "X-Mailer: PHP". phpversion() ."\r\n";

			mail($request->input('email'), $subject, $message, $headers);

			DB::commit();
			$request->session()->flash('success-message', 'Succesfully Inserted');
		} catch (\Exception $e) {
			DB::rollback();
			// something went wrong
			$request->session()->flash('error-message', 'Insert Failed');
		}
		return redirect('admin/partners');
	}

	function create_password($length) {
        $key = '';
        $keys = array_merge(range(0, 9), range('a', 'z'));

        for ($i = 0; $i < $length; $i++) {
            $key .= $keys[array_rand($keys)];
        }

        return $key;
    }

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{

		$partner_info = Partners::where('users.id',$id)
					->join('zones','zones.id', '=', 'users.zone_id')
					->select('users.*', 'zones.name as zone')
					->get();
					// print_r($partner_info->toArray());die('hello');
		return View('backend.partners.show',compact('partner_info'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		$partner_info = Partners::where('id',$id)->get();

		// DB::enableQueryLog();
		$assigned_brands = Partner_brands::select(DB::raw("array_to_string(array_agg(DISTINCT brand_id), ',') as brand_id"))
                     ->where('user_id','=',$id)
                     ->groupBy('user_id')
                     ->get();
        // print_r(DB::getQueryLog());
        // print_r($assigned_brands[0]->brand_id); die();
        $partner_brands = ($assigned_brands && $assigned_brands[0]->brand_id != '')?explode(",", $assigned_brands[0]->brand_id):array();
        
		$brands = Brands::all();
		$zones=Zones::get()->lists('name', 'id');
		
		return View('backend.partners.edit',compact('partner_info','brands','zones','partner_brands'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, UpdatePartnersFormRequest $request)
	{
		//
		DB::beginTransaction();
		try{
			$partner_info = Partners::where('id',$id)->get();

			$logo = $partner_info[0]->logo;
			if ($request->file('logo') && $request->file('logo')->isValid()) {
				$destinationPath = 'uploads/partners/logo'; // upload path
				$extension = $request->file('logo')->getClientOriginalExtension(); // getting image extension
				$logo = rand(11111,99999).'.'.$extension; // renameing image
				$request->file('logo')->move($destinationPath, $logo); // uploading file to given path
				@unlink('uploads/partners/logo/'.$partner_info[0]->logo);
			}

			$background_image = $partner_info[0]->background_image;
			if ($request->file('background_image') && $request->file('background_image')->isValid()) {
				$destinationPath = 'uploads/partners/backgrounds'; // upload path
				$extension = $request->file('background_image')->getClientOriginalExtension(); // getting image extension
				$background_image = rand(11111,99999).'.'.$extension; // renameing image
				$request->file('background_image')->move($destinationPath, $background_image); // uploading file to given path
				@unlink('uploads/partners/backgrounds/'.$partner_info[0]->background_image);
			}

			$partner = Partners::where('id',$id)->update([
				'name'=>$request->input('name'),
				'email'=>$request->input('email'),
				'contact_person'=>$request->input('contact_person'),
				'designation'=>$request->input('designation'),
				'address'=>$request->input('address'),
				'city'=>$request->input('city'),
				'phone'=>$request->input('phone'),
				'zone_id'=>$request->input('zone_id'),
				'logo'=>$logo,
				'background_image'=>$background_image,
				'is_facebook'=>$request->input('facebook_link'),
				'latitude' => $request->input('latitude'),
				'longitude' => $request->input('longitude'),
				'updated_by'=>\Auth::user()->id
				]);
			
			Partner_brands::where('user_id',$id)->update([
				'deleted_by'=>\Auth::user()->id,
				'deleted_at'=>date('Y-m-d H:i:s')
				]);

			foreach($request->input('brand_id') as $brand_id){
				$partner_brand = Partner_brands::create([
					'user_id'=>$id,
					'brand_id'=>$brand_id,
					'created_by'=>\Auth::user()->id,
					'updated_by'=>\Auth::user()->id
					]);
			}

			DB::commit();
			$request->session()->flash('success-message', 'Succesfully Updated');
		} catch (\Exception $e) {
			DB::rollback();
			// something went wrong
			$request->session()->flash('error-message', 'Update Failed');
		}
		return redirect('admin/partners');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id,Request $request)
	{
		//
		DB::beginTransaction();
		try{
			Partners::where('id',$id)->update([
				'deleted_by'=>\Auth::user()->id
				]);

			Partners::destroy($id);

			Partner_brands::where('user_id',$id)->update([
				'deleted_by'=>\Auth::user()->id
				]);

			Partner_brands::destroy($id);			

			DB::commit();
			$request->session()->flash('success-message', 'Succesfully Deleted');
		} catch (\Exception $e) {
			DB::rollback();
			// something went wrong
			$request->session()->flash('error-message', 'Delete Failed');
		}
		
		return redirect('admin/partners');
	}

	public function generate_qr_code()
	{
		$qr_code = rand(1000,9999);
		if (Partners::where('qr_code', '=', $qr_code)->exists()) {
			$this->generate_qr_code();
		}else{
		   return $qr_code;
		}
	}

	public function reset_password(Request $request)
	{
		$user_id = $request->input('id');
		$password = $request->input('new_password');
		$partner = Partners::where('id',$user_id)->update([
				'password'=>\Hash::make($password),
				'updated_by'=>\Auth::user()->id
				]);

		$partner_info = Partners::where('id',$user_id)->get();

		$subject = 'Password Reset Info';
		$message = "<html>
					    <body>
					    <p>Hi {$partner_info[0]->name}</p>

resources/views/backend/partners/create.blade.php
@extends('backend/app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body ">
			<div class="bg-light lter b-b wrapper-md">
				<h1 class="m-n font-thin h3">Create New Partner</h1>
			</div>
			<div class="wrapper-md" ng-controller="FormDemoCtrl">
				<div class="row">
				<div class="col-sm-12 col-md-12 col-xs-12">
				<div class="panel panel-default">
					<!-- <div class="panel-heading font-bold">
						Create New Partner
					</div> -->
					<div class="panel-body">
						<!-- @if (count($errors) > 0)
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif -->
						{!! Form::open(['route' => 'admin.partners.store','id'=>'partners-create','data-parsley-validate','files'=>true]) !!}
						{!! Form::hidden('type','partner',['id'=>'type']) !!}
						{!! Form::hidden('latitude','27.7172453',['id'=>'latitude']) !!}
						{!! Form::hidden('longitude','85.3239605',['id'=>'longitude']) !!}
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
									{!! Form::text('name', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('contact_person', 'Contact Person:', ['class' => 'control-label']) !!}
									{!! Form::text('contact_person', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('contact_person')) <p class="help-block">{{ $errors->first('contact_person') }}</p> @endif
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('email', 'Email:', ['class' => 'control-label']) !!}
									{!! Form::text('email', null, ['class' => 'form-control email required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('designation', 'Designation:', ['class' => 'control-label']) !!}
									{!! Form::text('designation', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('designation')) <p class="help-block">{{ $errors->first('designation') }}</p> @endif
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('city', 'City:', ['class' => 'control-label']) !!}
									{!! Form::text('city', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('city')) <p class="help-block">{{ $errors->first('city') }}</p> @endif
								</div>
								
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('address', 'Address:', ['class' => 'control-label']) !!}
									{!! Form::text('address', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('address')) <p class="help-block">{{ $errors->first('address') }}</p> @endif
								</div>
								
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('phone', 'Phone:', ['class' => 'control-label']) !!}
									{!! Form::input('number', 'phone', $value = null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('phone')) <p class="help-block">{{ $errors->first('phone') }}</p> @endif
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('zone_id', 'Zone:', ['class' => 'control-label']) !!}
									{!! Form::select('zone_id',array(null=>'Please Select Zone')+$zones,null,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select zone')) !!}

									@if ($errors->has('zone_id')) <p class="help-block">{{ $errors->first('zone_id') }}</p> @endif
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('logo', 'Logo:', ['class' => 'control-label']) !!}
									<div class="image_select">
										<input type="file" name="logo" id="file-1" class="inputfile inputfile-6" data-multiple-caption="{count} files selected" multiple />
										<label for="file-1"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Choose a Image&hellip;</strong></label>
									</div>										
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{!! Form::label('background_image', 'Background Image:', ['class' => 'control-label']) !!}
									<div class="image_select">
										<input type="file" name="background_image" id="file-2" class="inputfile inputfile-6" data-multiple-caption="{count} files selected" multiple />
										<label for="file-2"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Choose a Image&hellip;</strong></label>
									</div>										
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<div class="checkbox-lebel">
								{!! Form::label('brand_id', 'Brands:') !!}
							</div>							
							<div class="checkbox">								
								@foreach($brands as $brand)
									<label class="i-checks i-checks-sm">
							            <input type="checkbox" name='brand_id[]' value="{{$brand->id}}"><i></i> {{$brand->name}}
							        </label>									
								@endforeach
								@if ($errors->has('brand_id')) <p class="help-block">{{ $errors->first('brand_id') }}</p> @endif
							</div>
						</div>

						<div class="form-group">
							{!! Form::label('facebook_link', 'Facebook URL:', ['class' => 'control-label']) !!}
							{!! Form::text('facebook_link', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
						</div>

						<div class="form-group">
							<input id='search_address' name="search_address" class='form-control' type='text' value='kathmandu, Nepal' placeholder='Search Box'>
							<div id="display_map" style="height:500px"></div>							
						</div>
						
						<button type="submit" name="save_zone" class="btn btn-sm btn-primary">Submit</button>
						<button type="reset" class="btn btn-sm btn-primary" onclick="location.href = '<?php echo URL::to('admin/partners');?>'">Cancel</button>
						</form>
					</div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/backend/partners/index.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">Partners</h1>
		</div>
<div class="container">
		
		<a href="{{ asset('uploads/partners/partners.xlsx') }}"><button class="btn btn-success">Download Excel xlsx</button></a>
		
		<form style="border: 4px solid #a1a1a1;margin-top: 15px;padding: 10px;" action="{{ url('admin/importExcel') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<input type="file" name="import_file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
			<button type="submit" class="btn btn-primary">Import File</button>
		</form>
	</div>
		<div class="wrapper-md">
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{{url('admin/partners/create')}}" class="btn btn-sm btn-primary btn-addon"><i class="fa fa-plus"></i>Add New Partner</a>
				</div>
				<div class="table-responsive">
					<table ui-jq="dataTable" ui-options="" class="table table-striped m-b-none">
						<thead>
							<tr>
								<th style="width:20%">SN</th>
								<th style="width:25%">Name</th>
								<th>Contact Person</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						@if($partners)
							<?php $i = 1;?>
							@foreach($partners as $partner)
								<tr>
									<td>{{$i}}</td>
									<td>{{$partner->name}}</td>
									<td>{{$partner->contact_person}}</td>
									<td>
										<a href="{{ route('admin.partners.show',$partner->id) }}" class="view btn btn-success btn-single" data-toggle="tooltip" title="Detail"><i class="fa fa-file-text-o"></i></a>
										<a class="edit btn btn-success btn-single" data-toggle="tooltip" title="Edit" href="{{ route('admin.partners.edit', $partner->id) }}"><i class="fa fa-edit"></i></a>
										{!! Form::open(['method' => 'DELETE','class'=>'common-class' ,'route'=>['admin.partners.destroy', $partner->id],'onsubmit' => 'return confirm("Do you want to delete this partner?")']) !!}
										<!-- {!!Form::button('<i class="icon icon-trash"></i> ', array('type' => 'submit')); !!} -->
										{!!Form::button('<i class="icon icon-trash"></i> ', array(
									           'type' => 'submit',
									           'title' => 'Delete',
									           'data-toggle' => 'tooltip',
									           'class'=> 'btn btn-success btn-single',
									           'onclick'=>'return confirm("Are you sure?")'
									   	)); !!}
										{!! Form::close() !!}
										<a data-toggle="tooltip" title="Reset Password" href="javascript:void(0)" class="edit btn btn-success btn-single reset_password" id="{{$partner->id}}" data-partnername="{{$partner->name}}">Reset</a>
									</td>
								</tr>
								<?php $i++; ?>
							@endforeach
						@else
							No Partners added yet.
						@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="partnerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Reset Password for <span class="partnername"></span></h4>
			</div>
			{!! Form::open(['route'=>['admin.partners.reset_password'],'id'=>'reset_password_form']) !!}
			{!! Form::hidden('id', '',array('id'=>'reset_partner_id')) !!}
			<div class="modal-body">
					<div class="form-group">
						{!! Form::label('new_password', 'New Password',['class'=>'control-label']) !!}
						{!! Form::password('new_password',array('class'=>'form-control required ','data-trigger'=>'change focusout','data-required-message'=>'Please enter new password')) !!}
					</div>
					<div class="form-group">
						{!! Form::label('password', 'Retype Password',['class'=>'control-label']) !!}
						{!! Form::password('confirm_password',array('class'=>'form-control required ','data-trigger'=>'change focusout','data-required-message'=>'Please retype password')) !!}
					</div>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default cancel_change" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-primary change_password">Rest Password</button>
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="partnerResetModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Reset Password for <span class="partnername"></span></h4>
			</div>
			<div class="modal-body">					

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default cancel_change" data-dismiss="modal">Close</button>
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
@endsection

resources/views/backend/partners/show.blade.php
@extends('backend/app')
@section('content')
  <div id="content" class="app-content" role="main">
    <div class="app-content-body ">
      <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Partner Detail</h1>
      </div>
      <div class="wrapper-md" ng-controller="FormDemoCtrl">
        <div class="row">
        <div class="col-md-12">
        <div class="panel panel-default">
          <!-- <div class="panel-heading font-bold">
            Create New Zone
          </div> -->
          {!! Form::hidden('latitude',$partner_info[0]->latitude,['id'=>'latitude']) !!}
            {!! Form::hidden('longitude',$partner_info[0]->longitude,['id'=>'longitude']) !!}
          <div class="panel-body">
            <div class="row">
            <?php ?>
            <table>
              <tr>
                  <td>Image</td>                   
                  <td><img src="{{ asset('uploads/partners/logo/'.$partner_info[0]->logo)}}" style="height: 100px; margin-top: 10px;" /></td>
               </tr>
              <tr>
                  <td>Name</td>                   
                  <td>{{$partner_info[0]->name}}</td>
               </tr>
               <tr>
                  <td>Email</td>                   
                  <td>{{$partner_info[0]->email}}</td>
               </tr>
               <tr>
                  <td>Phone</td>                   
                  <td>{{$partner_info[0]->phone}}</td>
               </tr>
               <tr>
                  <td>Qr Code</td>                   
                  <td>{{$partner_info[0]->qr_code}}</td>
               </tr>
               <tr>
                  <td>Zone</td>                   
                  <td>{{$partner_info[0]->zone}}</td>
               </tr>
               <tr>
                  <td>Background Image</td>                   
                  <td><img src="{{ asset('uploads/partners/backgrounds/'.$partner_info[0]->background_image)}}" style="height: 100px; margin-top: 10px;" /></td>
               </tr>
                <tr>
                  <td>Description</td>                   
                  <td>{{$partner_info[0]->description}}</b></td>
               </tr>
              </table>
            </div>
         </div>
      </div>
      <div class="form-group">
           <div id="display_map" style="height:500px"></div>             
      </div>      
</div>
</div>
</div>
</div>
@endsection