app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', 'WelcomeController@index');

//Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/',     'HomeController@index');
Route::get('admin/home/', 'HomeController@index');

// Route::post('users/store', 'UserController@store');

Route::group(['prefix' => 'admin','middleware' => ['auth']], function(){
	Route::get('events/get_all', 'EventsController@get_all');
	Route::resource('events', 'EventsController');

	Route::get('offers/get_all', 'OffersController@get_all');
	Route::resource('offers', 'OffersController');

	Route::resource('redeemeds', 'RedeemedsController');	

	Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
});

Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function(){

	Route::resource('user', 'UserController');
	Route::get('brands/get_all','BrandsController@get_all');
	Route::resource('brands','BrandsController');

	Route::get('zones/get_all', 'ZonesController@get_all');
	Route::resource('zones', 'ZonesController');

	Route::get('partners/get_all', 'PartnersController@get_all');
	Route::resource('partners', 'PartnersController');


	Route::post('importExcel','PartnersController@importExcel');

	Route::post('reset_password',['as' => 'admin.partners.reset_password','uses' =>'PartnersController@reset_password']);
});

Route::group(['prefix'=>'admin'], function(){
Route::post('newpassword',['as' => 'admin.newpassword','uses' =>'UserController@newpassword']);
});

Route::group(['prefix'=>'v1'], function(){
	Route::post('users/store', 'UserController@store');
	Route::get('zones/list','ZonesController@nearbyzones');
	Route::get('partners/get_partners/{id}', 'PartnersController@get_partners');
	Route::get('partners/details/{id}','PartnersController@details');
	Route::get('offers/view/{offer_id}', 'OffersController@view_offer');
	Route::get('events/list','EventsController@nearbyevents');
	Route::get('events/view/{id}', 'EventsController@view_event');

	Route::get('events/notification', 'EventsController@event_notify');
	
	Route::post('redeemeds/redeem_offer', 'RedeemedsController@redeem_offer');
	Route::get('redeemeds/user_redeemed', 'RedeemedsController@user_redeem_offer');
	Route::get('zones/search', 'ZonesController@search_zones');
	Route::get('events/search', 'EventsController@search_events');
	Route::get('offers/list', 'OffersController@nearbyofffers');
	Route::get('offers/birthdayoffers/{user_id}', 'OffersController@birthday_offers');
	Route::get('offers/search', 'OffersController@search_offers');
	Route::get('notification', 'UserController@notify');	
	Route::post('users/location', 'UserController@user_location');	
	Route::post('users/favourite', 'UserController@user_favourites');
	Route::post('users/favouritelist', 'UserController@user_favourite_list');
});

app/Http/Controllers/OffersController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateOffersFormRequest;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Model\Offers;
use App\Model\Zones;
use App\Model\Partners;
use App\Model\Offer_partners;
use App\Model\Offer_zones;
use DB;
use Input;
use LaravelFCM\Message\OptionsBuilder;
use LaravelFCM\Message\PayloadDataBuilder;
use LaravelFCM\Message\PayloadNotificationBuilder;
use FCM;
use App\Model\Notifications;

class_alias(\LaravelFCM\Facades\FCM::class, 'FCM');
class_alias(\LaravelFCM\Facades\FCMGroup::class, 'FCMGroup');

class OffersController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		
		// DB::enableQueryLog();
		$data['type']=null;
		$data['upcomming_expired']=null;
		if(\Auth::user()->type == 'admin'){
			$offers = Offers::orderBy('id', 'desc');
		}elseif(\Auth::user()->type == 'partner'){
			$offers = Offers::where('created_by',\Auth::user()->id)->orderBy('id', 'desc');
		}
		if($request->exists('type') && $request->type!=''){

			$offers=$offers->where('type',$request->type);
			$data['type']=$request->type;
		}
		if($request->exists('upcomming_expired') && $request->upcomming_expired!=''){
		
			if($request->upcomming_expired=='upcomming'){
				$offers=$offers->whereDate('start_date','>',Carbon::today()->toDateString());
				$data['upcomming_expired']=$request->upcomming_expired;
			}
			
			if($request->upcomming_expired=='expired'){
				$offers=$offers->whereDate('end_date','<',Carbon::today()->toDateString());
				$data['upcomming_expired']=$request->upcomming_expired;
			}
		}

		$offers=$offers->get();
		// print_r(DB::getQueryLog());die('hello');
		// print_r($offers->toArray());die('hello');
		return View('backend.offers.index', compact('offers','data'));
	}

	public function get_all()
	{
		$offers = Offers::all();
		return response()->json(['aaData' => $offers]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		$offer_type = array('general'=>'General','birthday'=>'Birthday');
		$offer_valid_in = array('zones'=>'GB Zone Wise','partners'=>'Partner Wise');
		$zones=Zones::get()->lists('name', 'id');
		$partners=Partners::where('type','partner')->get()->lists('name', 'id');
		return View('backend.offers.create', compact('offer_type','offer_valid_in','zones','partners'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateOffersFormRequest $request)
	{
		//
		// print_r($request->all());die;
		$offer_datas = array();
		$offer_datas['image'] ='';
		if ($request->file('image') && $request->file('image')->isValid()) {
			$destinationPath = 'uploads/offers'; // upload path
			$extension = $request->file('image')->getClientOriginalExtension(); // getting image extension
			$offer_datas['image'] = rand(11111,99999).'.'.$extension; // renameing image
			$request->file('image')->move($destinationPath, $offer_datas['image']); // uploading file to given path
		}

		
		$offer_datas['type'] = $request->input('type');
		$offer_datas['title'] = $request->input('title');
		$offer_datas['description'] = $request->input('description');
		$offer_datas['created_by'] = \Auth::user()->id;
		$offer_datas['updated_by'] = \Auth::user()->id;

		if($request->input('type') == 'general'){
			$offer_datas['start_date'] = $request->input('start_date');
			$offer_datas['end_date'] = $request->input('end_date');
		}

		DB::beginTransaction();

		try{
			$offer = Offers::create($offer_datas);
			$offer_id = $offer->id;
			if(\Auth::user()->type == 'admin'){
		
				if($request->input('offer_valid_in') == 'zones'){
					foreach($request->input('zone_ids') as $key => $val){
						$offer_zone = Offer_zones::create([
							'offer_id'=>$offer_id,
							'zone_id' => $val,
							'created_by'=>\Auth::user()->id,
							'updated_by'=>\Auth::user()->id
							]);
					}
				}elseif($request->input('offer_valid_in') == 'partners'){
					foreach($request->input('partner_ids') as $key => $val){
						$offer_partner = Offer_partners::create([
							'offer_id'=>$offer_id,
							'user_id' => $val,
							'created_by'=>\Auth::user()->id,
							'updated_by'=>\Auth::user()->id
							]);
					}
				}
			}elseif(\Auth::user()->type == 'partner'){
				$offer_partner = Offer_partners::create([
							'offer_id'=>$offer_id,
							'user_id' =>\Auth::user()->id,
							'created_by'=>\Auth::user()->id,
							'updated_by'=>\Auth::user()->id
							]);
			}
			DB::commit();
			$request->session()->flash('success-message', 'Succesfully Inserted');
		} catch (\Exception $e) {
			DB::rollback();
			// something went wrong
			$request->session()->flash('error-message', 'Insert Failed');
		}
		
		if(Input::get('save_notify')) {
			$optionBuiler = new OptionsBuilder();
			$optionBuiler->setTimeToLive(60*20);
			$notification_title = $request->input('title');
			$notification_body = $request->input('description');


			$notificationBuilder = new PayloadNotificationBuilder($notification_title);
			$notificationBuilder->setBody($notification_body)
			                    ->setSound('default')
			                    ->setIcon('fcm_push_icon')
			                    ->setClickAction('FCM_PLUGIN_ACTIVITY');

			$dataBuilder = new PayloadDataBuilder();
			$dataBuilder->addData(['title' => $notification_title,'body'=>$notification_body,'type'=>'offer','id'=>$offer_id]);
			$option = $optionBuiler->build();
			$notification = $notificationBuilder->build();
			$data = $dataBuilder->build();

			if(isset($_GET['debug'])) {
				print_r($data);
				print_r($option);
				print_r($notification);
				die();
			}

			// You must change it to get your tokens
			
			$push_ids = Notifications::select(DB::raw('array_to_string(array_agg(DISTINCT push_id), \',\') as push_ids'))->get();
			$tokens = explode(",", $push_ids[0]->push_ids);

			
			$downstreamResponse = FCM::sendTo($tokens, $option, $notification,$data);
			 //print_r($downstreamResponse);
			echo "success count ".$downstreamResponse->numberSuccess();
			echo "failure count ".$downstreamResponse->numberFailure(); 
			echo "modifiction count ".$downstreamResponse->numberModification();

			//return Array - you must remove all this tokens in your database
			$downstreamResponse->tokensToDelete(); 

			//return Array (key : oldToken, value : new token - you must change the token in your database )
			$downstreamResponse->tokensToModify(); 

			//return Array - you should try to resend the message to the tokens in the array
			$downstreamResponse->tokensToRetry();

         
         }		

		return redirect('admin/offers');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$offer_info = Offers::where('id',$id)->get();

		$offer_partners = Offer_partners::with('user')->select('user_id')->where('offer_id',$id)->get();

		

		// $offer_partners = Offer_partners::select(DB::raw("array_to_string(array_agg(user_id), ',') as user_ids"))->where('offer_id',$id)->get();

		// $assigned_partners = ($offer_partners[0]->user_ids != "")?explode(",", $offer_partners[0]->user_ids):array();	

		$offer_zones = Offer_zones::with('zone')->select('zone_id')->where('offer_id',$id)->get();


		// $offer_zones = Offer_zones::select(DB::raw("array_to_string(array_agg(zone_id), ',') as zone_ids"))->where('offer_id',$id)->get();
		// $assigned_zones = ($offer_zones[0]->zone_ids != "")?explode(",", $offer_zones[0]->zone_ids):array();	
		
		if(!$offer_zones->isEmpty()){
			$offer_valid_type = 'GB Zone Wise';
		}else if(!$offer_partners->isEmpty()){
			$offer_valid_type = 'Partner Wise';
		}else{
			$offer_valid_type = '';
		}

		// if($offer_zones[0]->zone_ids != ""){
		// 	$offer_valid_type = 'zones';
		// }
		// if($offer_partners[0]->user_ids != ""){
		// 	$offer_valid_type = 'partners';
		// }

		// $offer_type = array('general'=>'General','birthday'=>'Birthday');
		// $offer_valid_in = array('zones'=>'GB Zone Wise','partners'=>'Partner Wise');
		// $zones=Zones::get()->lists('name', 'id');
		// $partners=Partners::where('type','partner')->get()->lists('name', 'id');
		
		return View('backend.offers.show',compact('offer_info','offer_partners','offer_zones','offer_valid_type'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		$offer_info = Offers::where('id',$id)->get();
		$offer_partners = Offer_partners::select(DB::raw("array_to_string(array_agg(DISTINCT user_id), ',') as user_ids"))->where('offer_id',$id)->get();
		$assigned_partners = ($offer_partners[0]->user_ids != "")?explode(",", $offer_partners[0]->user_ids):array();

		$offer_zones = Offer_zones::select(DB::raw("array_to_string(array_agg(DISTINCT zone_id), ',') as zone_ids"))->where('offer_id',$id)->get();
		$assigned_zones = ($offer_zones[0]->zone_ids != "")?explode(",", $offer_zones[0]->zone_ids):array();		
		
		$offer_valid_type = '';
		if($offer_zones[0]->zone_ids != ""){
			$offer_valid_type = 'zones';
		}
		if($offer_partners[0]->user_ids != ""){
			$offer_valid_type = 'partners';
		}

		$offer_type = array('general'=>'General','birthday'=>'Birthday');
		$offer_valid_in = array('zones'=>'GB Zone Wise','partners'=>'Partner Wise');
		$zones=Zones::get()->lists('name', 'id');
		$partners=Partners::where('type','partner')->get()->lists('name', 'id');
		
		return View('backend.offers.edit',compact('offer_info','offer_type','offer_valid_in','zones','partners','assigned_partners','assigned_zones','offer_valid_type'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, CreateOffersFormRequest $request)
	{
		//
		$offer_datas = array();
		$offer_datas['type'] = $request->input('type');

resources/views/backend/offers/create.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">New Offer</h1>
		</div>
		<div class="wrapper-md" ng-controller="FormDemoCtrl">
			<div class="row">
				<div class="col-sm-12 col-md-6 col-xs-6">
					<div class="panel panel-default">
						<div class="panel-heading font-bold">Add New Offer</div>
						<div class="panel-body">
							@if (count($errors) > 0)
								<div class="alert alert-danger">
									<ul>
										@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
										@endforeach
									</ul>
								</div>
							@endif
							{!! Form::open(['route' => 'admin.offers.store','data-parsley-validate','files'=>true]) !!}
								<?php if(Auth::user()->type == 'partner'):?>
									{!! Form::hidden('type','general',['id'=>'type']) !!}
								<?php endif;?>
								<div class="form-group">
									{!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
									{!! Form::text('title', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<div class="form-group">
									{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
									{!! Form::file('image', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>

								<?php if(Auth::user()->type == 'admin'):?>
								<div class="form-group">
									{!! Form::label('type', 'Type:', ['class' => 'control-label']) !!}
									{!! Form::select('type',array(null=>'Please Select')+$offer_type,null,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select offer', 'id'=>'offer_type')) !!}
								</div>
								<?php endif;?>
								<div class="form-group date_section" style="display: <?php (Auth::user()->type == 'admin')?'none':'block'?>;">
									{!! Form::label('start_date', 'Start Date:', ['class' => 'control-label']) !!}
									{!! Form::text('start_date', null, ['class' => 'form-control datepick required','data-trigger'=>'change focusout', 'id'=>'starting_date','ui-jq'=>'datepicker','ui-options'=>'{format: "yyyy-mm-dd",startDate: "$today_date"}','readonly'=>'readonly']) !!}
								</div>
								<div class="form-group date_section" style="display: <?php (Auth::user()->type == 'admin')?'none':'block'?>;">
									{!! Form::label('end_date', 'End Date:', ['class' => 'control-label']) !!}
									{!! Form::text('end_date', null, ['class' => 'form-control datepick required','data-trigger'=>'change focusout', 'id'=>'ending_date','ui-jq'=>'datepicker','ui-options'=>'{format: "yyyy-mm-dd",startDate: "$today_date"}','readonly'=>'readonly']) !!}
								</div>
								
								<?php if(Auth::user()->type == 'admin'):?>
									<div class="form-group">
										{!! Form::label('offer_valid_in', 'Offer Valid In:', ['class' => 'control-label']) !!}
										{!! Form::select('offer_valid_in',array(null=>'Please Select')+$offer_valid_in,null,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select','id'=>'offer_valid_in')) !!}
									</div>
									<div class="form-group" id="zone_section" style="display: none;">
										{!! Form::label('zone_id', 'Zone:', ['class' => 'control-label']) !!}
										{!! Form::select('zone_ids[]',array(null=>'Please Select')+$zones,null,array('class'=>'form-control','data-trigger'=>'change focusout','data-required-message'=>'Select','multiple'=>'multiple')) !!}
									</div>
									<div class="form-group" id="partner_section" style="display: none;">
										{!! Form::label('partner_id', 'Partner:', ['class' => 'control-label']) !!}
										{!! Form::select('partner_ids[]',array(null=>'Please Select')+$partners,null,array('class'=>'form-control','data-trigger'=>'change focusout','data-required-message'=>'Select','multiple'=>'multiple')) !!}
									</div>
								<?php endif;?>

								<div class="form-group">
									{!! Form::label('description', 'Description:', ['class' => 'control-label']) !!}
									{!! Form::textarea('description', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<button type="submit" name="save_offer" class="btn btn-sm btn-primary">Submit</button>
<button type="submit" name="save_notify" value="save_and_notify" style="display: none;" class="btn btn-sm notify_save btn-primary">Submit And Push</button>
								<button type="reset" class="btn btn-sm btn-primary" onclick="location.href = '<?php echo URL::to('admin/offers');?>'">Cancel</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/offers/edit.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">New Offer</h1>
		</div>
		<div class="wrapper-md" ng-controller="FormDemoCtrl">
			<div class="row">
				<div class="col-sm-12 col-md-6 col-xs-6">
					<div class="panel panel-default">
						<div class="panel-heading font-bold">Add New Offer</div>
						<div class="panel-body">
							@if (count($errors) > 0)
								<div class="alert alert-danger">
									<ul>
										@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
										@endforeach
									</ul>
								</div>
							@endif
							{!! Form::model($offer_info,['route' => ['admin.offers.update', $offer_info[0]->id], 'method' => 'patch','data-parsley-validate','files'=>true]) !!}
								
								<div class="form-group">
									{!! Form::label('title', 'Title:', ['class' => 'control-label']) !!}
									{!! Form::text('title', $offer_info[0]->title, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<div class="form-group">
									{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
									{!! Form::file('image', null, ['class' => 'form-control']) !!}
									<br />
									@if($offer_info[0]->image != '')
										<img src="{{ asset('uploads/offers/'.$offer_info[0]->image)}}" style="height: 100px; margin-top: 10px;" />
									@endif
								</div>
								

								<?php if(Auth::user()->type == 'admin'):?>
								<div class="form-group">
									{!! Form::label('type', 'Type:', ['class' => 'control-label']) !!}
									{!! Form::select('type',array(null=>'Please Select')+$offer_type,$offer_info[0]->type,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select offer', 'id'=>'offer_type')) !!}
								</div>
								<?php elseif(Auth::user()->type == 'partner'):?>
									{!! Form::hidden('type','general',['id'=>'type']) !!}
								<?php endif;?>

								<div class="form-group date_section" style="display: {{$offer_info[0]->type=='general'?'block':'none'}};">
									{!! Form::label('start_date', 'Start Date:', ['class' => 'control-label']) !!}
									{!! Form::text('start_date', $offer_info[0]->start_date, ['class' => 'form-control datepick required','data-trigger'=>'change focusout','id'=>'starting_date','ui-jq'=>'datepicker','ui-options'=>'{format: "yyyy-mm-dd",startDate: "$today_date"}','readonly'=>'readonly']) !!}
								</div>
								<div class="form-group date_section" style="display: {{$offer_info[0]->type=='general'?'block':'none'}};">
									{!! Form::label('end_date', 'End Date:', ['class' => 'control-label']) !!}
									{!! Form::text('end_date', $offer_info[0]->end_date, ['class' => 'form-control datepick required','data-trigger'=>'change focusout','id'=>'ending_date','ui-jq'=>'datepicker','ui-options'=>'{format: "yyyy-mm-dd",startDate: "$today_date"}','readonly'=>'readonly']) !!}
								</div>
								
								<?php if(Auth::user()->type == 'admin'):?>
									<div class="form-group">
										{!! Form::label('offer_valid_in', 'Offer Valid In:', ['class' => 'control-label']) !!}
										{!! Form::select('offer_valid_in',array(null=>'Please Select')+$offer_valid_in,$offer_valid_type,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select','id'=>'offer_valid_in')) !!}
									</div>
									<div class="form-group" id="zone_section" style="display: {{$offer_valid_type == 'zones'?'block':'none'}};">
										{!! Form::label('zone_id', 'Zone:', ['class' => 'control-label']) !!}
										{!! Form::select('zone_ids[]',array(null=>'Please Select')+$zones,$assigned_zones,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select', 'multiple'=>'multiple')) !!}
									</div>
									<div class="form-group" id="partner_section" style="display: {{$offer_valid_type=='partners'?'block':'none'}};">
										{!! Form::label('partner_id', 'Partner:', ['class' => 'control-label']) !!}
										{!! Form::select('partner_ids[]',array(null=>'Please Select')+$partners,$assigned_partners,array('class'=>'form-control required','data-trigger'=>'change focusout','data-required-message'=>'Select', 'multiple'=>'multiple')) !!}
									</div>
								<?php endif;?>
								<div class="form-group">
									{!! Form::label('description', 'Description:', ['class' => 'control-label']) !!}
									{!! Form::textarea('description', $offer_info[0]->description, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<button type="submit" name="save_offer" class="btn btn-sm btn-primary">Submit</button>
								<button type="reset" class="btn btn-sm btn-primary" onclick="location.href = '<?php echo URL::to('admin/offers');?>'">Cancel</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/offers/index.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">Offers</h1>
		</div>
	<div class="search-data  col-md-12">
						{!! Form::open(['method'=>'GET','url' => 'admin/offers/','class'=>'navbar-form navbar-left','id'=>'search_form_id','novalidate' => 'novalidate']) !!}					
							<div class="form-group">
								{!! Form::label('Type', 'Type') !!}
								{!! Form::select('type',array(null=>'Please Select','birthday'=>'Birthday','general'=>'General'),$data['type'],array('class'=>'form-control','data-trigger'=>'change focusout')) !!}
							</div>
							<div class="form-group">
								{!! Form::label('Upcomming_expired', 'Upcomming/Expired Offers') !!}
								{!! Form::select('upcomming_expired',array(null=>'Please Select','upcomming'=>'Upcomming Offers','expired'=>'Expired Offers'),$data['upcomming_expired'],array('class'=>'form-control','data-trigger'=>'change focusout')) !!}
							</div>
							
							{!! Form::submit('Search',array('class'=>'btn btn-info btn-single','id'=>'search_id')) !!}

						{!! Form::close() !!}
					</div>
		<div class="wrapper-md">
			
			<div class="panel panel-default">

				<div class="panel-heading">
					<a href="{{url('admin/offers/create')}}" class="btn btn-sm btn-primary btn-addon"><i class="fa fa-plus"></i>Add New Offer</a>
				</div>

				<div class="table-responsive">
					<table ui-jq="dataTable" ui-options="" class="table table-striped m-b-none">
						<thead>
							<tr>
								<th style="width:20%">SN</th>
								<th style="width:25%">Title</th>
								<th>Start Date</th>
								<th>End Date</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						@if($offers)
							<?php $i = 1; ?>
							@foreach($offers as $offer)
								<tr>
									<td>{{$i}}</td>
									<td>{{$offer->title}}</td>
									<td>{{$offer->start_date}}</td>
									<td>{{$offer->end_date}}</td>
									<td>
										<a href="{{ route('admin.offers.show',$offer->id) }}" class="view btn btn-success btn-single" data-toggle="tooltip" title="Detail"><i class="fa fa-file-text-o"></i></a>

										<a class="edit btn btn-success btn-single" data-toggle="tooltip" title="Edit" href="{{ route('admin.offers.edit', $offer->id) }}"><i class="fa fa-edit"></i></a>
										{!! Form::open(['method' => 'DELETE', 'route'=>['admin.offers.destroy', $offer->id],'onsubmit' => 'return confirm("Do you want to delete this offer?")']) !!}
										{!!Form::button('<i class="icon icon-trash"></i> ', array(
									           'type' => 'submit',
									           'title' => 'Delete',
									           'data-toggle' => 'tooltip',
									           'class'=> 'btn btn-success btn-single',
									           'onclick'=>'return confirm("Are you sure?")'
									   	)); !!}
										{!! Form::close() !!}
										<a href="#" class="btn btn-sm btn-primary btn-addon">Re Run</a>
									</td>
								</tr>
								<?php $i++; ?>
							@endforeach
						@else
							No offers added yet.
						@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection