app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', 'WelcomeController@index');

//Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/',     'HomeController@index');
Route::get('admin/home/', 'HomeController@index');

// Route::post('users/store', 'UserController@store');

Route::group(['prefix' => 'admin','middleware' => ['auth']], function(){
	Route::get('events/get_all', 'EventsController@get_all');
	Route::resource('events', 'EventsController');

	Route::get('offers/get_all', 'OffersController@get_all');
	Route::resource('offers', 'OffersController');

	Route::resource('redeemeds', 'RedeemedsController');	

	Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
});

Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function(){

	Route::resource('user', 'UserController');
	Route::get('brands/get_all','BrandsController@get_all');
	Route::resource('brands','BrandsController');

	Route::get('zones/get_all', 'ZonesController@get_all');
	Route::resource('zones', 'ZonesController');

	Route::get('partners/get_all', 'PartnersController@get_all');
	Route::resource('partners', 'PartnersController');


	Route::post('importExcel','PartnersController@importExcel');

	Route::post('reset_password',['as' => 'admin.partners.reset_password','uses' =>'PartnersController@reset_password']);
});

Route::group(['prefix'=>'admin'], function(){
Route::post('newpassword',['as' => 'admin.newpassword','uses' =>'UserController@newpassword']);
});

Route::group(['prefix'=>'v1'], function(){
	Route::post('users/store', 'UserController@store');
	Route::get('zones/list','ZonesController@nearbyzones');
	Route::get('partners/get_partners/{id}', 'PartnersController@get_partners');
	Route::get('partners/details/{id}','PartnersController@details');
	Route::get('offers/view/{offer_id}', 'OffersController@view_offer');
	Route::get('events/list','EventsController@nearbyevents');
	Route::get('events/view/{id}', 'EventsController@view_event');

	Route::get('events/notification', 'EventsController@event_notify');
	
	Route::post('redeemeds/redeem_offer', 'RedeemedsController@redeem_offer');
	Route::get('redeemeds/user_redeemed', 'RedeemedsController@user_redeem_offer');
	Route::get('zones/search', 'ZonesController@search_zones');
	Route::get('events/search', 'EventsController@search_events');
	Route::get('offers/list', 'OffersController@nearbyofffers');
	Route::get('offers/birthdayoffers/{user_id}', 'OffersController@birthday_offers');
	Route::get('offers/search', 'OffersController@search_offers');
	Route::get('notification', 'UserController@notify');	
	Route::post('users/location', 'UserController@user_location');	
	Route::post('users/favourite', 'UserController@user_favourites');
	Route::post('users/favouritelist', 'UserController@user_favourite_list');
});

app/Http/Controllers/ZonesController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateZonesFormRequest;
use App\Http\Requests\UpdateZonesFormRequest;

use Illuminate\Http\Request;
use App\Model\Zones;
use App\Model\Offers;
use DB;

class ZonesController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		$zones = Zones::orderBy('id', 'desc')->get();
		return View('backend.zones.index', compact('zones'));
	}

	public function get_all()
	{
		$zones = Zones::all();
		return response()->json(['aaData' => $zones]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		return View('backend.zones.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateZonesFormRequest $request)
	{
		//
		$fileName = '';
		if ($request->file('image') && $request->file('image')->isValid()) {
			$destinationPath = 'uploads/zones'; // upload path
			$extension = $request->file('image')->getClientOriginalExtension(); // getting image extension
			$fileName = rand(11111,99999).'.'.$extension; // renameing image
			$request->file('image')->move($destinationPath, $fileName); // uploading file to given path
		}

		$zone = Zones::create([
			'name'=>$request->input('name'),
			'image'=>$fileName,
			'district'=>$request->input('district'),
			'latitude'=>$request->input('latitude'),
			'longitude'=>$request->input('longitude'),
			'radius'=>$request->input('radius'),
			'created_by'=>\Auth::user()->id,
			'updated_by'=>\Auth::user()->id
			]);
		if($zone){
			$request->session()->flash('success-message', 'Succesfully Inserted');
		}else{
			$request->session()->flash('error-message', 'Insert Failed');
		}

		return redirect('admin/zones');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		$zone_info = Zones::where('id',$id)->get();
		return View('backend.zones.edit',compact('zone_info'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, UpdateZonesFormRequest $request)
	{
		//
		$zone_info = Zones::where('id',$id)->get();
		$fileName = $zone_info[0]->image;
		if ($request->file('image')) {
			$destinationPath = 'uploads/zones'; // upload path
			$extension = $request->file('image')->getClientOriginalExtension(); // getting image extension
			$fileName = rand(11111,99999).'.'.$extension; // renameing image
			$request->file('image')->move($destinationPath, $fileName); // uploading file to given path
			@unlink('uploads/zones/'.$zone_info[0]->image);
		}
		$zone = Zones::where('id',$id)->update([
			'name'=>$request->input('name'),
			'image'=>$fileName,
			'district'=>$request->input('district'),
			'latitude'=>$request->input('latitude'),
			'longitude'=>$request->input('longitude'),
			'radius'=>$request->input('radius'),
			'updated_by'=>\Auth::user()->id
			]);
		if($zone){
			$request->session()->flash('success-message', 'Succesfully Updated');
		}else{
			$request->session()->flash('error-message', 'Update Failed');
		}
		return redirect('admin/zones');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id,Request $request)
	{
		//
		Zones::where('id',$id)->update([
			'deleted_by'=>\Auth::user()->id
			]);

		$result= Zones::destroy($id);
		if($result){
			$request->session()->flash('success-message','Succesfully Deleted');
		}else{
			$request->session()->flash('error-message', 'Delete Failed');
		}
		return redirect('admin/zones');
	}

	public function nearbyzones(Request $request)
	{
		$per_page = 5;
		$latitude = $request->input('lat');
		$longitude = $request->input('lng');
		$offset = ($request->input('offset'))?$request->input('offset'):0;
		$required_offset = ($offset>0)?(($offset-1)*$per_page):$offset;

		$offers = array();
		if($offset == 0 || $offset == 1){
			$offers = Offers::select('id','title','image')->where('image','!=','')->where('type','=','general')->whereDate('end_date','>=',date('Y-m-d'))->offset(0)->limit(3)->get();
		}

		$results = DB::select('SELECT tbl.id, tbl.name, image, tbl.latitude,tbl.longitude, radius, distance_in_km, array_to_string(array_agg(DISTINCT users.name), \',\') as offers_at FROM (SELECT id,name,image, latitude, longitude, radius, (3959 * acos(cos(radians(:lat :: FLOAT)) * cos(radians(latitude :: FLOAT)) * cos(radians(longitude :: FLOAT) - radians(:lng :: FLOAT)) + sin(radians(:lat :: FLOAT)) * sin(radians(latitude :: FLOAT)))) * 1.6 AS distance_in_km FROM zones WHERE deleted_by IS NULL) AS tbl LEFT JOIN users on (users.zone_id = tbl.id AND users.deleted_by IS NULL) GROUP BY tbl.id, tbl.name, image, tbl.latitude,tbl.longitude, radius, distance_in_km order by distance_in_km ASC OFFSET :offset LIMIT :per_page', ['lat'=>$latitude,'lng'=>$longitude, 'offset'=>$required_offset, 'per_page'=>$per_page]);
		return response()->json(["offers"=>$offers, "zones"=>$results,  "status"=>1], 201);
	}

	public function search_zones(Request $request)
	{
		$per_page = 5;
		$keywords = strtolower($request->keywords);

		$offset = ($request->input('offset'))?$request->input('offset'):0;
		$required_offset = ($offset>0)?(($offset-1)*$per_page):$offset;


		// $zones = Zones::select(DB::raw('zones.id, zones.name, array_to_string(array_agg(users.name),\',\') as offers_at'))
		// 				->where(function ($query) use ($keywords) {
		// 	                $query->where('zones.name', 'ilike', '%'.$keywords.'%')
		// 	                      ->orWhere('district', 'ilike', '%' . $keywords . '%');
		// 	            })
		// 				->leftJoin('users','users.zone_id','=','zones.id')
		// 				->whereNull('users.deleted_by')
		// 				->groupBy('zones.id','zones.name')
		// 				->offset($required_offset)
  //               		->limit($per_page)
		// 				->get();
		$zones = Zones::select(DB::raw('zones.id, zones.name,zones.latitude,zones.longitude,zones.radius, image, array_to_string(array_agg(DISTINCT users.name),\',\') as offers_at'))
						->where(function ($query) use ($keywords){
							$query->where('zones.name', 'ilike', '%'.$keywords.'%')
									->orWhere('zones.district', 'ilike', '%'.$keywords.'%');
						})
						->leftJoin('users','users.zone_id','=','zones.id')
						->where('users.type','=','partner')
						->whereNull('users.deleted_at')
						->groupBy('zones.id','zones.name')
						->offset($required_offset)
						->limit($per_page)
						->get();
		return response()->json(['zones'=>$zones,"status"=>1], 200);

	}

}

resources/views/backend/zones/create.blade.php
@extends('backend/app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body ">
			<div class="bg-light lter b-b wrapper-md">
				<h1 class="m-n font-thin h3">Create New Zone</h1>
			</div>
			<div class="wrapper-md" ng-controller="FormDemoCtrl">
				<div class="row">
				<div class="col-md-12">
				<div class="panel panel-default">
					<!-- <div class="panel-heading font-bold">
						Create New Zone
					</div> -->
					<div class="panel-body">
						<div class="row">
							
						</div>
						<!-- @if (count($errors) > 0)
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif -->
						{!! Form::open(['route' => 'admin.zones.store','id'=>'zones-create','data-parsley-validate','files'=>true]) !!}
						{!! Form::hidden('latitude','27.7172453',['id'=>'latitude']) !!}
						{!! Form::hidden('longitude','85.3239605',['id'=>'longitude']) !!}
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									{!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
									{!! Form::text('name', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
								</div>
								<div class="form-group">
									{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
									{!! Form::file('image', null, ['class' => 'form-control']) !!}									
								</div>

								<div class="form-group">
									{!! Form::label('district', 'District:', ['class' => 'control-label']) !!}
									{!! Form::text('district', null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('district')) <p class="help-block">{{ $errors->first('district') }}</p> @endif
								</div>
								<div class="form-group">
									<input id='search_address' name="search_address" class='form-control' type='text' value='kathmandu, Nepal' placeholder='Search Box'>
									<div id="display_map" style="height:500px"></div>							
								</div>
								<div class="form-group">
									{!! Form::label('radius', 'Radius:', ['class' => 'control-label']) !!}
									{!! Form::input('number', 'radius', $value = null, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}

									@if ($errors->has('radius')) <p class="help-block">{{ $errors->first('radius') }}</p> @endif
								</div>
								<button type="submit" name="save_zone" class="btn btn-sm btn-primary">Submit</button>
								<button type="reset" class="btn btn-sm btn-primary" onclick="location.href = '<?php echo URL::to('admin/zones');?>'">Cancel</button>
							</form>
							</div>
						</div>
						
					</div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/backend/zones/edit.blade.php
@extends('backend/app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body ">
			<div class="bg-light lter b-b wrapper-md">
				<h1 class="m-n font-thin h3">Update Zone</h1>
			</div>
			<div class="wrapper-md" ng-controller="FormDemoCtrl">
				<div class="row">
				<div class="col-sm-12 col-md-12 col-xs-12">
				<div class="panel panel-default">
					<div class="panel-heading font-bold">
						Update Zone
					</div>
					<div class="panel-body">
						@if (count($errors) > 0)
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif
						{!! Form::model($zone_info,['id'=>'zones-update','route' => ['admin.zones.update', $zone_info[0]->id], 'method' => 'patch','data-parsley-validate','files'=>true]) !!}
						{!! Form::hidden('id',$zone_info[0]->id,['id'=>'id']) !!}
						{!! Form::hidden('latitude',$zone_info[0]->latitude,['id'=>'latitude']) !!}
						{!! Form::hidden('longitude',$zone_info[0]->longitude,['id'=>'longitude']) !!}
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									{!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
									{!! Form::text('name', $zone_info[0]->name, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>

								<div class="form-group">
									{!! Form::label('image', 'Image:', ['class' => 'control-label']) !!}
									{!! Form::file('image', null, ['class' => 'form-control']) !!}
									<br />
									@if($zone_info[0]->image != '')
										<img src="{{ asset('uploads/zones/'.$zone_info[0]->image)}}" style="height: 50px; margin-top: 10px;" />
									@endif
								</div>

								<div class="form-group">
									{!! Form::label('district', 'District:', ['class' => 'control-label']) !!}
									{!! Form::text('district', $zone_info[0]->district, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<div class="form-group">
									<input id='search_address' name="search_address" class='form-control' type='text' value='kathmandu, Nepal' placeholder='Search Box'>
									<div id="display_map" style="height:500px"></div>							
								</div>
										<div class="form-group">
									{!! Form::label('radius', 'Radius:', ['class' => 'control-label']) !!}
									{!! Form::input('number', 'radius', $value = $zone_info[0]->radius, ['class' => 'form-control required','data-trigger'=>'change focusout']) !!}
								</div>
								<button type="submit" name="save_zone" class="btn btn-sm btn-primary">Submit</button>
							</div>
						</div>
						
						</form>
					</div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/backend/zones/index.blade.php
@extends('backend/app')

@section('content')
<div id="content" class="app-content" role="main">
	<div class="app-content-body ">
		<div class="bg-light lter b-b wrapper-md">
			<h1 class="m-n font-thin h3">Zones</h1>
		</div>
		<div class="wrapper-md">
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{{url('admin/zones/create')}}" class="btn btn-sm btn-primary btn-addon"><i class="fa fa-plus"></i>Add New Zone</a>
				</div>
				<div class="table-responsive">
					<table ui-jq="dataTable" ui-options="" class="table table-striped m-b-none">
						<thead>
							<tr>
								<th style="width:20%">SN</th>
								<th style="width:25%">Name</th>
								<th>District</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						@if($zones)
							<?php $i = 1; ?>
							@foreach($zones as $zone)
								<tr>
									<td>{{$i}}</td>
									<td>{{$zone->name}}</td>
									<td>{{$zone->district}}</td>
									<td>
										<a class="edit btn btn-success btn-single" data-toggle="tooltip" title="Edit" href="{{ route('admin.zones.edit', $zone->id) }}"><i class="fa fa-edit"></i></a>
										{!! Form::open(['method' => 'DELETE', 'route'=>['admin.zones.destroy', $zone->id],'onsubmit' => 'return confirm("Do you want to delete this zone?")']) !!}
										<!-- {!!Form::button('<i class="icon icon-trash"></i> ', array('type' => 'submit')); !!} -->
										{!!Form::button('<i class="icon icon-trash"></i> ', array(
									           'type' => 'submit',
									           'title' => 'Delete',
									           'data-toggle' => 'tooltip',
									           'class'=> 'btn btn-success btn-single',
									           'onclick'=>'return confirm("Are you sure?")'
									   	)); !!}
										{!! Form::close() !!}
									</td>
								</tr>
								<?php $i++; ?>
							@endforeach
						@else
							No zones added yet.
						@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection